/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MEOWLER_MEOWLER_PB_H_INCLUDED
#define PB_MEOWLER_MEOWLER_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _meowler_ColorLabel {
    meowler_ColorLabel_COLOR_NONE = 0,
    meowler_ColorLabel_COLOR_RED = 1,
    meowler_ColorLabel_COLOR_YELLOW = 2,
    meowler_ColorLabel_COLOR_GREEN = 3
} meowler_ColorLabel;

typedef enum _meowler_LogLevel {
    meowler_LogLevel_LOG_DEBUG = 0,
    meowler_LogLevel_LOG_INFO = 1,
    meowler_LogLevel_LOG_WARN = 2,
    meowler_LogLevel_LOG_ERROR = 3
} meowler_LogLevel;

typedef enum _meowler_RobotAction {
    meowler_RobotAction_ROBOT_ACT_NONE = 0,
    meowler_RobotAction_ROBOT_ACT_STATUS = 1,
    meowler_RobotAction_ROBOT_ACT_STOP = 2, /* wheels stop */
    meowler_RobotAction_ROBOT_ACT_PING = 3,
    meowler_RobotAction_ROBOT_ACT_CAL_COLOR = 4,
    meowler_RobotAction_ROBOT_ACT_ARM_CENTER = 5,
    meowler_RobotAction_ROBOT_ACT_ARM_DEMO = 6
} meowler_RobotAction;

/* Struct definitions */
typedef struct _meowler_ArmCommand {
    bool has_base;
    uint32_t base; /* 0..180 */
    bool has_height;
    uint32_t height;
    bool has_grip;
    uint32_t grip;
    bool has_speed_dps;
    uint16_t speed_dps; /* 0 => default */
    bool has_action;
    uint8_t action; /* 0 none 1 status 2 center 3 demo */
} meowler_ArmCommand;

typedef struct _meowler_ArmStatus {
    uint16_t base;
    uint16_t height;
    uint16_t grip;
    bool pca_ok;
    bool moving;
    uint16_t distance_mm;
    bool tof_ok;
    bool imu_ok;
    int32_t yaw_cdeg;
    int32_t pitch_cdeg;
    int32_t roll_cdeg;
} meowler_ArmStatus;

typedef struct _meowler_DriveCommand {
    int16_t left; /* −255..255 */
    int16_t right;
} meowler_DriveCommand;

typedef struct _meowler_DriveStatus {
    int16_t left;
    int16_t right;
    int32_t enc_left;
    int32_t enc_right;
} meowler_DriveStatus;

/* Nano SoftSerial — wheels (L298N) + arm (PCA9685) + VL53L0X on Nano I2C */
typedef struct _meowler_NanoCommand {
    bool has_drive;
    meowler_DriveCommand drive;
    bool has_arm;
    meowler_ArmCommand arm;
    /* 0 none  2 stop wheels  5 arm center  6 arm demo */
    bool has_action;
    uint8_t action;
} meowler_NanoCommand;

typedef struct _meowler_NanoStatus {
    bool has_drive;
    meowler_DriveStatus drive;
    uint16_t base;
    uint16_t height;
    uint16_t grip;
    bool pca_ok;
    bool moving;
    uint16_t distance_mm;
    bool tof_ok;
} meowler_NanoStatus;

typedef struct _meowler_RobotCommand {
    bool has_drive;
    meowler_DriveCommand drive;
    bool has_arm;
    meowler_ArmCommand arm;
    bool has_action;
    meowler_RobotAction action;
} meowler_RobotCommand;

/* High-rate live telemetry (prefer this over chatty multi-message streams) */
typedef struct _meowler_RobotTelemetry {
    uint16_t seq;
    uint32_t t_ms;
    meowler_ColorLabel color;
    uint8_t conf;
    uint16_t r_us;
    uint16_t g_us;
    uint16_t b_us;
    uint16_t c_us;
    int16_t left;
    int16_t right;
    int32_t enc_l;
    int32_t enc_r;
    uint16_t base;
    uint16_t height;
    uint16_t grip;
    uint16_t distance_mm;
    int32_t yaw_cdeg;
    int32_t pitch_cdeg;
    int32_t roll_cdeg;
    /* bit0 nano_ok  bit1 pca_ok  bit2 tof_ok  bit3 imu_ok
 bit4 moving   bit5 color_cal  bit6 espnow_peer */
    uint16_t flags;
} meowler_RobotTelemetry;

typedef PB_BYTES_ARRAY_T(40) meowler_DebugLog_text_t;
typedef struct _meowler_DebugLog {
    uint32_t t_ms;
    meowler_LogLevel level;
    meowler_DebugLog_text_t text; /* short ASCII, max 40 */
} meowler_DebugLog;

/* USB (laptop↔hub) and ESP-NOW (hub↔robot) */
typedef struct _meowler_LinkMessage {
    pb_size_t which_payload;
    union {
        meowler_RobotCommand cmd;
        meowler_RobotTelemetry telem;
        meowler_DebugLog log;
    } payload;
} meowler_LinkMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _meowler_ColorLabel_MIN meowler_ColorLabel_COLOR_NONE
#define _meowler_ColorLabel_MAX meowler_ColorLabel_COLOR_GREEN
#define _meowler_ColorLabel_ARRAYSIZE ((meowler_ColorLabel)(meowler_ColorLabel_COLOR_GREEN+1))

#define _meowler_LogLevel_MIN meowler_LogLevel_LOG_DEBUG
#define _meowler_LogLevel_MAX meowler_LogLevel_LOG_ERROR
#define _meowler_LogLevel_ARRAYSIZE ((meowler_LogLevel)(meowler_LogLevel_LOG_ERROR+1))

#define _meowler_RobotAction_MIN meowler_RobotAction_ROBOT_ACT_NONE
#define _meowler_RobotAction_MAX meowler_RobotAction_ROBOT_ACT_ARM_DEMO
#define _meowler_RobotAction_ARRAYSIZE ((meowler_RobotAction)(meowler_RobotAction_ROBOT_ACT_ARM_DEMO+1))







#define meowler_RobotCommand_action_ENUMTYPE meowler_RobotAction

#define meowler_RobotTelemetry_color_ENUMTYPE meowler_ColorLabel

#define meowler_DebugLog_level_ENUMTYPE meowler_LogLevel



/* Initializer values for message structs */
#define meowler_ArmCommand_init_default          {false, 0, false, 0, false, 0, false, 0, false, 0}
#define meowler_ArmStatus_init_default           {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define meowler_DriveCommand_init_default        {0, 0}
#define meowler_DriveStatus_init_default         {0, 0, 0, 0}
#define meowler_NanoCommand_init_default         {false, meowler_DriveCommand_init_default, false, meowler_ArmCommand_init_default, false, 0}
#define meowler_NanoStatus_init_default          {false, meowler_DriveStatus_init_default, 0, 0, 0, 0, 0, 0, 0}
#define meowler_RobotCommand_init_default        {false, meowler_DriveCommand_init_default, false, meowler_ArmCommand_init_default, false, _meowler_RobotAction_MIN}
#define meowler_RobotTelemetry_init_default      {0, 0, _meowler_ColorLabel_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define meowler_DebugLog_init_default            {0, _meowler_LogLevel_MIN, {0, {0}}}
#define meowler_LinkMessage_init_default         {0, {meowler_RobotCommand_init_default}}
#define meowler_ArmCommand_init_zero             {false, 0, false, 0, false, 0, false, 0, false, 0}
#define meowler_ArmStatus_init_zero              {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define meowler_DriveCommand_init_zero           {0, 0}
#define meowler_DriveStatus_init_zero            {0, 0, 0, 0}
#define meowler_NanoCommand_init_zero            {false, meowler_DriveCommand_init_zero, false, meowler_ArmCommand_init_zero, false, 0}
#define meowler_NanoStatus_init_zero             {false, meowler_DriveStatus_init_zero, 0, 0, 0, 0, 0, 0, 0}
#define meowler_RobotCommand_init_zero           {false, meowler_DriveCommand_init_zero, false, meowler_ArmCommand_init_zero, false, _meowler_RobotAction_MIN}
#define meowler_RobotTelemetry_init_zero         {0, 0, _meowler_ColorLabel_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define meowler_DebugLog_init_zero               {0, _meowler_LogLevel_MIN, {0, {0}}}
#define meowler_LinkMessage_init_zero            {0, {meowler_RobotCommand_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define meowler_ArmCommand_base_tag              1
#define meowler_ArmCommand_height_tag            2
#define meowler_ArmCommand_grip_tag              3
#define meowler_ArmCommand_speed_dps_tag         4
#define meowler_ArmCommand_action_tag            5
#define meowler_ArmStatus_base_tag               1
#define meowler_ArmStatus_height_tag             2
#define meowler_ArmStatus_grip_tag               3
#define meowler_ArmStatus_pca_ok_tag             4
#define meowler_ArmStatus_moving_tag             5
#define meowler_ArmStatus_distance_mm_tag        6
#define meowler_ArmStatus_tof_ok_tag             7
#define meowler_ArmStatus_imu_ok_tag             8
#define meowler_ArmStatus_yaw_cdeg_tag           9
#define meowler_ArmStatus_pitch_cdeg_tag         10
#define meowler_ArmStatus_roll_cdeg_tag          11
#define meowler_DriveCommand_left_tag            1
#define meowler_DriveCommand_right_tag           2
#define meowler_DriveStatus_left_tag             1
#define meowler_DriveStatus_right_tag            2
#define meowler_DriveStatus_enc_left_tag         3
#define meowler_DriveStatus_enc_right_tag        4
#define meowler_NanoCommand_drive_tag            1
#define meowler_NanoCommand_arm_tag              2
#define meowler_NanoCommand_action_tag           3
#define meowler_NanoStatus_drive_tag             1
#define meowler_NanoStatus_base_tag              2
#define meowler_NanoStatus_height_tag            3
#define meowler_NanoStatus_grip_tag              4
#define meowler_NanoStatus_pca_ok_tag            5
#define meowler_NanoStatus_moving_tag            6
#define meowler_NanoStatus_distance_mm_tag       7
#define meowler_NanoStatus_tof_ok_tag            8
#define meowler_RobotCommand_drive_tag           1
#define meowler_RobotCommand_arm_tag             2
#define meowler_RobotCommand_action_tag          3
#define meowler_RobotTelemetry_seq_tag           1
#define meowler_RobotTelemetry_t_ms_tag          2
#define meowler_RobotTelemetry_color_tag         3
#define meowler_RobotTelemetry_conf_tag          4
#define meowler_RobotTelemetry_r_us_tag          5
#define meowler_RobotTelemetry_g_us_tag          6
#define meowler_RobotTelemetry_b_us_tag          7
#define meowler_RobotTelemetry_c_us_tag          8
#define meowler_RobotTelemetry_left_tag          9
#define meowler_RobotTelemetry_right_tag         10
#define meowler_RobotTelemetry_enc_l_tag         11
#define meowler_RobotTelemetry_enc_r_tag         12
#define meowler_RobotTelemetry_base_tag          13
#define meowler_RobotTelemetry_height_tag        14
#define meowler_RobotTelemetry_grip_tag          15
#define meowler_RobotTelemetry_distance_mm_tag   16
#define meowler_RobotTelemetry_yaw_cdeg_tag      17
#define meowler_RobotTelemetry_pitch_cdeg_tag    18
#define meowler_RobotTelemetry_roll_cdeg_tag     19
#define meowler_RobotTelemetry_flags_tag         20
#define meowler_DebugLog_t_ms_tag                1
#define meowler_DebugLog_level_tag               2
#define meowler_DebugLog_text_tag                3
#define meowler_LinkMessage_cmd_tag              1
#define meowler_LinkMessage_telem_tag            2
#define meowler_LinkMessage_log_tag              3

/* Struct field encoding specification for nanopb */
#define meowler_ArmCommand_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   base,              1) \
X(a, STATIC,   OPTIONAL, UINT32,   height,            2) \
X(a, STATIC,   OPTIONAL, UINT32,   grip,              3) \
X(a, STATIC,   OPTIONAL, UINT32,   speed_dps,         4) \
X(a, STATIC,   OPTIONAL, UINT32,   action,            5)
#define meowler_ArmCommand_CALLBACK NULL
#define meowler_ArmCommand_DEFAULT NULL

#define meowler_ArmStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   base,              1) \
X(a, STATIC,   SINGULAR, UINT32,   height,            2) \
X(a, STATIC,   SINGULAR, UINT32,   grip,              3) \
X(a, STATIC,   SINGULAR, BOOL,     pca_ok,            4) \
X(a, STATIC,   SINGULAR, BOOL,     moving,            5) \
X(a, STATIC,   SINGULAR, UINT32,   distance_mm,       6) \
X(a, STATIC,   SINGULAR, BOOL,     tof_ok,            7) \
X(a, STATIC,   SINGULAR, BOOL,     imu_ok,            8) \
X(a, STATIC,   SINGULAR, SINT32,   yaw_cdeg,          9) \
X(a, STATIC,   SINGULAR, SINT32,   pitch_cdeg,       10) \
X(a, STATIC,   SINGULAR, SINT32,   roll_cdeg,        11)
#define meowler_ArmStatus_CALLBACK NULL
#define meowler_ArmStatus_DEFAULT NULL

#define meowler_DriveCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   left,              1) \
X(a, STATIC,   SINGULAR, SINT32,   right,             2)
#define meowler_DriveCommand_CALLBACK NULL
#define meowler_DriveCommand_DEFAULT NULL

#define meowler_DriveStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   left,              1) \
X(a, STATIC,   SINGULAR, SINT32,   right,             2) \
X(a, STATIC,   SINGULAR, SINT32,   enc_left,          3) \
X(a, STATIC,   SINGULAR, SINT32,   enc_right,         4)
#define meowler_DriveStatus_CALLBACK NULL
#define meowler_DriveStatus_DEFAULT NULL

#define meowler_NanoCommand_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  drive,             1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  arm,               2) \
X(a, STATIC,   OPTIONAL, UINT32,   action,            3)
#define meowler_NanoCommand_CALLBACK NULL
#define meowler_NanoCommand_DEFAULT NULL
#define meowler_NanoCommand_drive_MSGTYPE meowler_DriveCommand
#define meowler_NanoCommand_arm_MSGTYPE meowler_ArmCommand

#define meowler_NanoStatus_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  drive,             1) \
X(a, STATIC,   SINGULAR, UINT32,   base,              2) \
X(a, STATIC,   SINGULAR, UINT32,   height,            3) \
X(a, STATIC,   SINGULAR, UINT32,   grip,              4) \
X(a, STATIC,   SINGULAR, BOOL,     pca_ok,            5) \
X(a, STATIC,   SINGULAR, BOOL,     moving,            6) \
X(a, STATIC,   SINGULAR, UINT32,   distance_mm,       7) \
X(a, STATIC,   SINGULAR, BOOL,     tof_ok,            8)
#define meowler_NanoStatus_CALLBACK NULL
#define meowler_NanoStatus_DEFAULT NULL
#define meowler_NanoStatus_drive_MSGTYPE meowler_DriveStatus

#define meowler_RobotCommand_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  drive,             1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  arm,               2) \
X(a, STATIC,   OPTIONAL, UENUM,    action,            3)
#define meowler_RobotCommand_CALLBACK NULL
#define meowler_RobotCommand_DEFAULT NULL
#define meowler_RobotCommand_drive_MSGTYPE meowler_DriveCommand
#define meowler_RobotCommand_arm_MSGTYPE meowler_ArmCommand

#define meowler_RobotTelemetry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   seq,               1) \
X(a, STATIC,   SINGULAR, UINT32,   t_ms,              2) \
X(a, STATIC,   SINGULAR, UENUM,    color,             3) \
X(a, STATIC,   SINGULAR, UINT32,   conf,              4) \
X(a, STATIC,   SINGULAR, UINT32,   r_us,              5) \
X(a, STATIC,   SINGULAR, UINT32,   g_us,              6) \
X(a, STATIC,   SINGULAR, UINT32,   b_us,              7) \
X(a, STATIC,   SINGULAR, UINT32,   c_us,              8) \
X(a, STATIC,   SINGULAR, SINT32,   left,              9) \
X(a, STATIC,   SINGULAR, SINT32,   right,            10) \
X(a, STATIC,   SINGULAR, SINT32,   enc_l,            11) \
X(a, STATIC,   SINGULAR, SINT32,   enc_r,            12) \
X(a, STATIC,   SINGULAR, UINT32,   base,             13) \
X(a, STATIC,   SINGULAR, UINT32,   height,           14) \
X(a, STATIC,   SINGULAR, UINT32,   grip,             15) \
X(a, STATIC,   SINGULAR, UINT32,   distance_mm,      16) \
X(a, STATIC,   SINGULAR, SINT32,   yaw_cdeg,         17) \
X(a, STATIC,   SINGULAR, SINT32,   pitch_cdeg,       18) \
X(a, STATIC,   SINGULAR, SINT32,   roll_cdeg,        19) \
X(a, STATIC,   SINGULAR, UINT32,   flags,            20)
#define meowler_RobotTelemetry_CALLBACK NULL
#define meowler_RobotTelemetry_DEFAULT NULL

#define meowler_DebugLog_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   t_ms,              1) \
X(a, STATIC,   SINGULAR, UENUM,    level,             2) \
X(a, STATIC,   SINGULAR, BYTES,    text,              3)
#define meowler_DebugLog_CALLBACK NULL
#define meowler_DebugLog_DEFAULT NULL

#define meowler_LinkMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,cmd,payload.cmd),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,telem,payload.telem),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,log,payload.log),   3)
#define meowler_LinkMessage_CALLBACK NULL
#define meowler_LinkMessage_DEFAULT NULL
#define meowler_LinkMessage_payload_cmd_MSGTYPE meowler_RobotCommand
#define meowler_LinkMessage_payload_telem_MSGTYPE meowler_RobotTelemetry
#define meowler_LinkMessage_payload_log_MSGTYPE meowler_DebugLog

extern const pb_msgdesc_t meowler_ArmCommand_msg;
extern const pb_msgdesc_t meowler_ArmStatus_msg;
extern const pb_msgdesc_t meowler_DriveCommand_msg;
extern const pb_msgdesc_t meowler_DriveStatus_msg;
extern const pb_msgdesc_t meowler_NanoCommand_msg;
extern const pb_msgdesc_t meowler_NanoStatus_msg;
extern const pb_msgdesc_t meowler_RobotCommand_msg;
extern const pb_msgdesc_t meowler_RobotTelemetry_msg;
extern const pb_msgdesc_t meowler_DebugLog_msg;
extern const pb_msgdesc_t meowler_LinkMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define meowler_ArmCommand_fields &meowler_ArmCommand_msg
#define meowler_ArmStatus_fields &meowler_ArmStatus_msg
#define meowler_DriveCommand_fields &meowler_DriveCommand_msg
#define meowler_DriveStatus_fields &meowler_DriveStatus_msg
#define meowler_NanoCommand_fields &meowler_NanoCommand_msg
#define meowler_NanoStatus_fields &meowler_NanoStatus_msg
#define meowler_RobotCommand_fields &meowler_RobotCommand_msg
#define meowler_RobotTelemetry_fields &meowler_RobotTelemetry_msg
#define meowler_DebugLog_fields &meowler_DebugLog_msg
#define meowler_LinkMessage_fields &meowler_LinkMessage_msg

/* Maximum encoded size of messages (where known) */
#define MEOWLER_MEOWLER_PB_H_MAX_SIZE            meowler_LinkMessage_size
#define meowler_ArmCommand_size                  25
#define meowler_ArmStatus_size                   42
#define meowler_DebugLog_size                    50
#define meowler_DriveCommand_size                8
#define meowler_DriveStatus_size                 20
#define meowler_LinkMessage_size                 96
#define meowler_NanoCommand_size                 40
#define meowler_NanoStatus_size                  44
#define meowler_RobotCommand_size                39
#define meowler_RobotTelemetry_size              94

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
