/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MEOWLER_MEOWLER_PB_H_INCLUDED
#define PB_MEOWLER_MEOWLER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _meowler_Drive {
    int32_t left; /* -255..255 */
    int32_t right; /* -255..255 */
} meowler_Drive;

typedef struct _meowler_Arm {
    int32_t base; /* 0..180 */
    int32_t height; /* 0..180 */
    int32_t grip; /* 0..180 */
    bool set_base;
    bool set_height;
    bool set_grip;
} meowler_Arm;

/* PCA CH15 — SG90 360° continuous (UM conveyor belt) */
typedef struct _meowler_Conveyor {
    int32_t speed; /* -255..255 · 0 = stop */
} meowler_Conveyor;

/* TCS3200 calibration / teach-in (RED·YELLOW·GREEN only) */
typedef struct _meowler_ColorCal {
    /* 0=white-balance  1=teach RED  2=teach YELLOW  3=teach GREEN
 4=clear taught centroids  5=factory reset gains+centroids */
    uint32_t mode;
} meowler_ColorCal;

/* Host → robot: start/stop onboard capture. Robot streams RecEvent back. */
typedef struct _meowler_RecCtrl {
    uint32_t action; /* 1=start  2=stop */
    char name[32];
} meowler_RecCtrl;

/* Robot → host: one packed timeline event (same opcodes as binary .rpm).
 op: 0=begin  1=drive  2=arm  3=stop  4=center  5=zero  6=conveyor  7=motor_test  255=end */
typedef struct _meowler_RecEvent {
    uint32_t t_ms;
    uint32_t op;
    int32_t a; /* drive.left / arm.base / conveyor.speed */
    int32_t b; /* drive.right / arm.height */
    int32_t c; /* arm.grip */
    uint32_t mask; /* arm field mask: 1=base 2=height 4=grip */
    uint32_t count; /* event count on begin/end */
    char name[32];
} meowler_RecEvent;

/* ---- Protobuf WiFi OTA (dual ota_0 / ota_1) ----
 Host: OtaCmd begin → chunk* → finish → apply
 Robot: streams OtaStatus; on apply reboots into new partition (otadata rollback if bad) */
typedef struct _meowler_OtaBegin {
    uint32_t raw_size; /* uncompressed .bin bytes */
    uint32_t raw_crc32; /* CRC-32 (zlib/binascii) of uncompressed */
    uint32_t packed_size; /* wire payload bytes */
    uint32_t codec; /* 0=raw  1=zlib */
    char version[24]; /* optional label */
} meowler_OtaBegin;

typedef PB_BYTES_ARRAY_T(4096) meowler_OtaChunk_data_t;
typedef struct _meowler_OtaChunk {
    uint32_t offset; /* byte offset into packed stream */
    meowler_OtaChunk_data_t data; /* up to 4096 bytes */
} meowler_OtaChunk;

typedef struct _meowler_OtaCmd {
    /* 1=begin  2=chunk  3=finish  4=abort  5=apply(reboot)  6=query status */
    uint32_t action;
    bool has_begin;
    meowler_OtaBegin begin;
    bool has_chunk;
    meowler_OtaChunk chunk;
} meowler_OtaCmd;

typedef struct _meowler_OtaStatus {
    /* 0=idle  1=receiving  2=ready  3=applying  4=error  5=rebooting */
    uint32_t state;
    uint32_t received; /* packed bytes received */
    uint32_t packed_size;
    uint32_t written; /* uncompressed bytes written to OTA slot */
    uint32_t error; /* 0=ok else fault code */
    char detail[48];
} meowler_OtaStatus;

typedef struct _meowler_ClientToRobot {
    pb_size_t which_op;
    union {
        meowler_Drive drive;
        meowler_Arm arm;
        bool stop;
        bool center;
        bool zero;
        bool motor_test;
        bool get_telem;
        meowler_Conveyor conveyor;
        meowler_ColorCal color_cal;
        meowler_RecCtrl rec;
        meowler_OtaCmd ota;
    } op;
} meowler_ClientToRobot;

typedef struct _meowler_Telemetry {
    uint32_t distance_mm;
    int32_t cmd_l;
    int32_t cmd_r;
    int32_t base;
    int32_t height;
    int32_t grip;
    bool pca_ok;
    bool tof_ok;
    bool imu_ok;
    bool wifi_ok;
    int32_t enc_l;
    int32_t enc_r;
    int32_t wheel_l_mm;
    int32_t wheel_r_mm;
    int32_t tof_disp_mm;
    int32_t yaw_cdeg;
    int32_t pitch_cdeg;
    int32_t roll_cdeg;
    uint32_t color; /* 0 UNKNOWN  1 RED  2 YELLOW  3 GREEN */
    uint32_t color_conf; /* internal confidence 0..99 (not a colour class) */
    /* Fields 21–27 reserved / unused in UI — keep wire-compatible, always 0 */
    uint32_t color_r;
    uint32_t color_g;
    uint32_t color_b;
    uint32_t color_rp;
    uint32_t color_gp;
    uint32_t color_bp;
    uint32_t color_cp;
    int32_t conveyor; /* -255..255 · PCA CH15 SG90-360 */
} meowler_Telemetry;

typedef struct _meowler_Hello {
    uint32_t ip; /* IPv4 as uint32 (network byte order) */
    uint32_t port;
    bool pca_ok;
    bool tof_ok;
    bool imu_ok;
} meowler_Hello;

/* Framed on Serial (and optionally TCP) — same uint32le | payload as TCP. */
typedef struct _meowler_Log {
    /* 0=debug  1=info  2=warn  3=error */
    uint32_t level;
    char text[120];
} meowler_Log;

typedef struct _meowler_RobotToClient {
    pb_size_t which_msg;
    union {
        meowler_Hello hello;
        meowler_Telemetry telem;
        uint32_t ack; /* 0 = ok */
        meowler_Log log;
        meowler_RecEvent rec;
        meowler_OtaStatus ota;
    } msg;
} meowler_RobotToClient;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define meowler_Drive_init_default               {0, 0}
#define meowler_Arm_init_default                 {0, 0, 0, 0, 0, 0}
#define meowler_Conveyor_init_default            {0}
#define meowler_ColorCal_init_default            {0}
#define meowler_RecCtrl_init_default             {0, ""}
#define meowler_RecEvent_init_default            {0, 0, 0, 0, 0, 0, 0, ""}
#define meowler_OtaBegin_init_default            {0, 0, 0, 0, ""}
#define meowler_OtaChunk_init_default            {0, {0, {0}}}
#define meowler_OtaCmd_init_default              {0, false, meowler_OtaBegin_init_default, false, meowler_OtaChunk_init_default}
#define meowler_OtaStatus_init_default           {0, 0, 0, 0, 0, ""}
#define meowler_ClientToRobot_init_default       {0, {meowler_Drive_init_default}}
#define meowler_Telemetry_init_default           {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define meowler_Hello_init_default               {0, 0, 0, 0, 0}
#define meowler_Log_init_default                 {0, ""}
#define meowler_RobotToClient_init_default       {0, {meowler_Hello_init_default}}
#define meowler_Drive_init_zero                  {0, 0}
#define meowler_Arm_init_zero                    {0, 0, 0, 0, 0, 0}
#define meowler_Conveyor_init_zero               {0}
#define meowler_ColorCal_init_zero               {0}
#define meowler_RecCtrl_init_zero                {0, ""}
#define meowler_RecEvent_init_zero               {0, 0, 0, 0, 0, 0, 0, ""}
#define meowler_OtaBegin_init_zero               {0, 0, 0, 0, ""}
#define meowler_OtaChunk_init_zero               {0, {0, {0}}}
#define meowler_OtaCmd_init_zero                 {0, false, meowler_OtaBegin_init_zero, false, meowler_OtaChunk_init_zero}
#define meowler_OtaStatus_init_zero              {0, 0, 0, 0, 0, ""}
#define meowler_ClientToRobot_init_zero          {0, {meowler_Drive_init_zero}}
#define meowler_Telemetry_init_zero              {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define meowler_Hello_init_zero                  {0, 0, 0, 0, 0}
#define meowler_Log_init_zero                    {0, ""}
#define meowler_RobotToClient_init_zero          {0, {meowler_Hello_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define meowler_Drive_left_tag                   1
#define meowler_Drive_right_tag                  2
#define meowler_Arm_base_tag                     1
#define meowler_Arm_height_tag                   2
#define meowler_Arm_grip_tag                     3
#define meowler_Arm_set_base_tag                 4
#define meowler_Arm_set_height_tag               5
#define meowler_Arm_set_grip_tag                 6
#define meowler_Conveyor_speed_tag               1
#define meowler_ColorCal_mode_tag                1
#define meowler_RecCtrl_action_tag               1
#define meowler_RecCtrl_name_tag                 2
#define meowler_RecEvent_t_ms_tag                1
#define meowler_RecEvent_op_tag                  2
#define meowler_RecEvent_a_tag                   3
#define meowler_RecEvent_b_tag                   4
#define meowler_RecEvent_c_tag                   5
#define meowler_RecEvent_mask_tag                6
#define meowler_RecEvent_count_tag               7
#define meowler_RecEvent_name_tag                8
#define meowler_OtaBegin_raw_size_tag            1
#define meowler_OtaBegin_raw_crc32_tag           2
#define meowler_OtaBegin_packed_size_tag         3
#define meowler_OtaBegin_codec_tag               4
#define meowler_OtaBegin_version_tag             5
#define meowler_OtaChunk_offset_tag              1
#define meowler_OtaChunk_data_tag                2
#define meowler_OtaCmd_action_tag                1
#define meowler_OtaCmd_begin_tag                 2
#define meowler_OtaCmd_chunk_tag                 3
#define meowler_OtaStatus_state_tag              1
#define meowler_OtaStatus_received_tag           2
#define meowler_OtaStatus_packed_size_tag        3
#define meowler_OtaStatus_written_tag            4
#define meowler_OtaStatus_error_tag              5
#define meowler_OtaStatus_detail_tag             6
#define meowler_ClientToRobot_drive_tag          1
#define meowler_ClientToRobot_arm_tag            2
#define meowler_ClientToRobot_stop_tag           3
#define meowler_ClientToRobot_center_tag         4
#define meowler_ClientToRobot_zero_tag           5
#define meowler_ClientToRobot_motor_test_tag     6
#define meowler_ClientToRobot_get_telem_tag      7
#define meowler_ClientToRobot_conveyor_tag       8
#define meowler_ClientToRobot_color_cal_tag      9
#define meowler_ClientToRobot_rec_tag            10
#define meowler_ClientToRobot_ota_tag            11
#define meowler_Telemetry_distance_mm_tag        1
#define meowler_Telemetry_cmd_l_tag              2
#define meowler_Telemetry_cmd_r_tag              3
#define meowler_Telemetry_base_tag               4
#define meowler_Telemetry_height_tag             5
#define meowler_Telemetry_grip_tag               6
#define meowler_Telemetry_pca_ok_tag             7
#define meowler_Telemetry_tof_ok_tag             8
#define meowler_Telemetry_imu_ok_tag             9
#define meowler_Telemetry_wifi_ok_tag            10
#define meowler_Telemetry_enc_l_tag              11
#define meowler_Telemetry_enc_r_tag              12
#define meowler_Telemetry_wheel_l_mm_tag         13
#define meowler_Telemetry_wheel_r_mm_tag         14
#define meowler_Telemetry_tof_disp_mm_tag        15
#define meowler_Telemetry_yaw_cdeg_tag           16
#define meowler_Telemetry_pitch_cdeg_tag         17
#define meowler_Telemetry_roll_cdeg_tag          18
#define meowler_Telemetry_color_tag              19
#define meowler_Telemetry_color_conf_tag         20
#define meowler_Telemetry_color_r_tag            21
#define meowler_Telemetry_color_g_tag            22
#define meowler_Telemetry_color_b_tag            23
#define meowler_Telemetry_color_rp_tag           24
#define meowler_Telemetry_color_gp_tag           25
#define meowler_Telemetry_color_bp_tag           26
#define meowler_Telemetry_color_cp_tag           27
#define meowler_Telemetry_conveyor_tag           28
#define meowler_Hello_ip_tag                     1
#define meowler_Hello_port_tag                   2
#define meowler_Hello_pca_ok_tag                 3
#define meowler_Hello_tof_ok_tag                 4
#define meowler_Hello_imu_ok_tag                 5
#define meowler_Log_level_tag                    1
#define meowler_Log_text_tag                     2
#define meowler_RobotToClient_hello_tag          1
#define meowler_RobotToClient_telem_tag          2
#define meowler_RobotToClient_ack_tag            3
#define meowler_RobotToClient_log_tag            4
#define meowler_RobotToClient_rec_tag            5
#define meowler_RobotToClient_ota_tag            6

/* Struct field encoding specification for nanopb */
#define meowler_Drive_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    left,              1) \
X(a, STATIC,   SINGULAR, INT32,    right,             2)
#define meowler_Drive_CALLBACK NULL
#define meowler_Drive_DEFAULT NULL

#define meowler_Arm_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    base,              1) \
X(a, STATIC,   SINGULAR, INT32,    height,            2) \
X(a, STATIC,   SINGULAR, INT32,    grip,              3) \
X(a, STATIC,   SINGULAR, BOOL,     set_base,          4) \
X(a, STATIC,   SINGULAR, BOOL,     set_height,        5) \
X(a, STATIC,   SINGULAR, BOOL,     set_grip,          6)
#define meowler_Arm_CALLBACK NULL
#define meowler_Arm_DEFAULT NULL

#define meowler_Conveyor_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    speed,             1)
#define meowler_Conveyor_CALLBACK NULL
#define meowler_Conveyor_DEFAULT NULL

#define meowler_ColorCal_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   mode,              1)
#define meowler_ColorCal_CALLBACK NULL
#define meowler_ColorCal_DEFAULT NULL

#define meowler_RecCtrl_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   action,            1) \
X(a, STATIC,   SINGULAR, STRING,   name,              2)
#define meowler_RecCtrl_CALLBACK NULL
#define meowler_RecCtrl_DEFAULT NULL

#define meowler_RecEvent_FIELDLIST(X, a_) \
X(a_, STATIC,   SINGULAR, UINT32,   t_ms,              1) \
X(a_, STATIC,   SINGULAR, UINT32,   op,                2) \
X(a_, STATIC,   SINGULAR, INT32,    a,                 3) \
X(a_, STATIC,   SINGULAR, INT32,    b,                 4) \
X(a_, STATIC,   SINGULAR, INT32,    c,                 5) \
X(a_, STATIC,   SINGULAR, UINT32,   mask,              6) \
X(a_, STATIC,   SINGULAR, UINT32,   count,             7) \
X(a_, STATIC,   SINGULAR, STRING,   name,              8)
#define meowler_RecEvent_CALLBACK NULL
#define meowler_RecEvent_DEFAULT NULL

#define meowler_OtaBegin_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   raw_size,          1) \
X(a, STATIC,   SINGULAR, UINT32,   raw_crc32,         2) \
X(a, STATIC,   SINGULAR, UINT32,   packed_size,       3) \
X(a, STATIC,   SINGULAR, UINT32,   codec,             4) \
X(a, STATIC,   SINGULAR, STRING,   version,           5)
#define meowler_OtaBegin_CALLBACK NULL
#define meowler_OtaBegin_DEFAULT NULL

#define meowler_OtaChunk_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   offset,            1) \
X(a, STATIC,   SINGULAR, BYTES,    data,              2)
#define meowler_OtaChunk_CALLBACK NULL
#define meowler_OtaChunk_DEFAULT NULL

#define meowler_OtaCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   action,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  begin,             2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  chunk,             3)
#define meowler_OtaCmd_CALLBACK NULL
#define meowler_OtaCmd_DEFAULT NULL
#define meowler_OtaCmd_begin_MSGTYPE meowler_OtaBegin
#define meowler_OtaCmd_chunk_MSGTYPE meowler_OtaChunk

#define meowler_OtaStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   state,             1) \
X(a, STATIC,   SINGULAR, UINT32,   received,          2) \
X(a, STATIC,   SINGULAR, UINT32,   packed_size,       3) \
X(a, STATIC,   SINGULAR, UINT32,   written,           4) \
X(a, STATIC,   SINGULAR, UINT32,   error,             5) \
X(a, STATIC,   SINGULAR, STRING,   detail,            6)
#define meowler_OtaStatus_CALLBACK NULL
#define meowler_OtaStatus_DEFAULT NULL

#define meowler_ClientToRobot_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (op,drive,op.drive),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (op,arm,op.arm),   2) \
X(a, STATIC,   ONEOF,    BOOL,     (op,stop,op.stop),   3) \
X(a, STATIC,   ONEOF,    BOOL,     (op,center,op.center),   4) \
X(a, STATIC,   ONEOF,    BOOL,     (op,zero,op.zero),   5) \
X(a, STATIC,   ONEOF,    BOOL,     (op,motor_test,op.motor_test),   6) \
X(a, STATIC,   ONEOF,    BOOL,     (op,get_telem,op.get_telem),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (op,conveyor,op.conveyor),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (op,color_cal,op.color_cal),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (op,rec,op.rec),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (op,ota,op.ota),  11)
#define meowler_ClientToRobot_CALLBACK NULL
#define meowler_ClientToRobot_DEFAULT NULL
#define meowler_ClientToRobot_op_drive_MSGTYPE meowler_Drive
#define meowler_ClientToRobot_op_arm_MSGTYPE meowler_Arm
#define meowler_ClientToRobot_op_conveyor_MSGTYPE meowler_Conveyor
#define meowler_ClientToRobot_op_color_cal_MSGTYPE meowler_ColorCal
#define meowler_ClientToRobot_op_rec_MSGTYPE meowler_RecCtrl
#define meowler_ClientToRobot_op_ota_MSGTYPE meowler_OtaCmd

#define meowler_Telemetry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   distance_mm,       1) \
X(a, STATIC,   SINGULAR, INT32,    cmd_l,             2) \
X(a, STATIC,   SINGULAR, INT32,    cmd_r,             3) \
X(a, STATIC,   SINGULAR, INT32,    base,              4) \
X(a, STATIC,   SINGULAR, INT32,    height,            5) \
X(a, STATIC,   SINGULAR, INT32,    grip,              6) \
X(a, STATIC,   SINGULAR, BOOL,     pca_ok,            7) \
X(a, STATIC,   SINGULAR, BOOL,     tof_ok,            8) \
X(a, STATIC,   SINGULAR, BOOL,     imu_ok,            9) \
X(a, STATIC,   SINGULAR, BOOL,     wifi_ok,          10) \
X(a, STATIC,   SINGULAR, INT32,    enc_l,            11) \
X(a, STATIC,   SINGULAR, INT32,    enc_r,            12) \
X(a, STATIC,   SINGULAR, INT32,    wheel_l_mm,       13) \
X(a, STATIC,   SINGULAR, INT32,    wheel_r_mm,       14) \
X(a, STATIC,   SINGULAR, INT32,    tof_disp_mm,      15) \
X(a, STATIC,   SINGULAR, INT32,    yaw_cdeg,         16) \
X(a, STATIC,   SINGULAR, INT32,    pitch_cdeg,       17) \
X(a, STATIC,   SINGULAR, INT32,    roll_cdeg,        18) \
X(a, STATIC,   SINGULAR, UINT32,   color,            19) \
X(a, STATIC,   SINGULAR, UINT32,   color_conf,       20) \
X(a, STATIC,   SINGULAR, UINT32,   color_r,          21) \
X(a, STATIC,   SINGULAR, UINT32,   color_g,          22) \
X(a, STATIC,   SINGULAR, UINT32,   color_b,          23) \
X(a, STATIC,   SINGULAR, UINT32,   color_rp,         24) \
X(a, STATIC,   SINGULAR, UINT32,   color_gp,         25) \
X(a, STATIC,   SINGULAR, UINT32,   color_bp,         26) \
X(a, STATIC,   SINGULAR, UINT32,   color_cp,         27) \
X(a, STATIC,   SINGULAR, INT32,    conveyor,         28)
#define meowler_Telemetry_CALLBACK NULL
#define meowler_Telemetry_DEFAULT NULL

#define meowler_Hello_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ip,                1) \
X(a, STATIC,   SINGULAR, UINT32,   port,              2) \
X(a, STATIC,   SINGULAR, BOOL,     pca_ok,            3) \
X(a, STATIC,   SINGULAR, BOOL,     tof_ok,            4) \
X(a, STATIC,   SINGULAR, BOOL,     imu_ok,            5)
#define meowler_Hello_CALLBACK NULL
#define meowler_Hello_DEFAULT NULL

#define meowler_Log_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   level,             1) \
X(a, STATIC,   SINGULAR, STRING,   text,              2)
#define meowler_Log_CALLBACK NULL
#define meowler_Log_DEFAULT NULL

#define meowler_RobotToClient_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,hello,msg.hello),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,telem,msg.telem),   2) \
X(a, STATIC,   ONEOF,    UINT32,   (msg,ack,msg.ack),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,log,msg.log),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,rec,msg.rec),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,ota,msg.ota),   6)
#define meowler_RobotToClient_CALLBACK NULL
#define meowler_RobotToClient_DEFAULT NULL
#define meowler_RobotToClient_msg_hello_MSGTYPE meowler_Hello
#define meowler_RobotToClient_msg_telem_MSGTYPE meowler_Telemetry
#define meowler_RobotToClient_msg_log_MSGTYPE meowler_Log
#define meowler_RobotToClient_msg_rec_MSGTYPE meowler_RecEvent
#define meowler_RobotToClient_msg_ota_MSGTYPE meowler_OtaStatus

extern const pb_msgdesc_t meowler_Drive_msg;
extern const pb_msgdesc_t meowler_Arm_msg;
extern const pb_msgdesc_t meowler_Conveyor_msg;
extern const pb_msgdesc_t meowler_ColorCal_msg;
extern const pb_msgdesc_t meowler_RecCtrl_msg;
extern const pb_msgdesc_t meowler_RecEvent_msg;
extern const pb_msgdesc_t meowler_OtaBegin_msg;
extern const pb_msgdesc_t meowler_OtaChunk_msg;
extern const pb_msgdesc_t meowler_OtaCmd_msg;
extern const pb_msgdesc_t meowler_OtaStatus_msg;
extern const pb_msgdesc_t meowler_ClientToRobot_msg;
extern const pb_msgdesc_t meowler_Telemetry_msg;
extern const pb_msgdesc_t meowler_Hello_msg;
extern const pb_msgdesc_t meowler_Log_msg;
extern const pb_msgdesc_t meowler_RobotToClient_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define meowler_Drive_fields &meowler_Drive_msg
#define meowler_Arm_fields &meowler_Arm_msg
#define meowler_Conveyor_fields &meowler_Conveyor_msg
#define meowler_ColorCal_fields &meowler_ColorCal_msg
#define meowler_RecCtrl_fields &meowler_RecCtrl_msg
#define meowler_RecEvent_fields &meowler_RecEvent_msg
#define meowler_OtaBegin_fields &meowler_OtaBegin_msg
#define meowler_OtaChunk_fields &meowler_OtaChunk_msg
#define meowler_OtaCmd_fields &meowler_OtaCmd_msg
#define meowler_OtaStatus_fields &meowler_OtaStatus_msg
#define meowler_ClientToRobot_fields &meowler_ClientToRobot_msg
#define meowler_Telemetry_fields &meowler_Telemetry_msg
#define meowler_Hello_fields &meowler_Hello_msg
#define meowler_Log_fields &meowler_Log_msg
#define meowler_RobotToClient_fields &meowler_RobotToClient_msg

/* Maximum encoded size of messages (where known) */
#define MEOWLER_MEOWLER_PB_H_MAX_SIZE            meowler_ClientToRobot_size
#define meowler_Arm_size                         39
#define meowler_ClientToRobot_size               4168
#define meowler_ColorCal_size                    6
#define meowler_Conveyor_size                    11
#define meowler_Drive_size                       22
#define meowler_Hello_size                       18
#define meowler_Log_size                         127
#define meowler_OtaBegin_size                    49
#define meowler_OtaChunk_size                    4105
#define meowler_OtaCmd_size                      4165
#define meowler_OtaStatus_size                   79
#define meowler_RecCtrl_size                     39
#define meowler_RecEvent_size                    90
#define meowler_RobotToClient_size               238
#define meowler_Telemetry_size                   235

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
