/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MEOWLER_MEOWLER_PB_H_INCLUDED
#define PB_MEOWLER_MEOWLER_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Host -> Nano */
typedef struct _meowler_ArmCommand {
    /* Absolute targets 0..180; omit field to leave that axis unchanged */
    bool has_base;
    uint32_t base;
    bool has_height;
    uint32_t height;
    bool has_grip;
    uint32_t grip;
    /* Max slew rate for this move (deg/s). 0 or omit => firmware default. */
    bool has_speed_dps;
    uint16_t speed_dps;
    /* 0=none 1=status 2=center 3=demo */
    bool has_action;
    uint8_t action;
} meowler_ArmCommand;

/* Nano -> Host */
typedef struct _meowler_ArmStatus {
    uint16_t base;
    uint16_t height;
    uint16_t grip;
    bool pca_ok;
    bool moving;
    /* VL53L0X ToF (mm). 0 + tof_ok=false => sensor missing / timeout */
    uint16_t distance_mm;
    bool tof_ok;
    /* BNO085 / BNO080 game-rotation Euler (centidegrees) */
    bool imu_ok;
    int32_t yaw_cdeg;
    int32_t pitch_cdeg;
    int32_t roll_cdeg;
} meowler_ArmStatus;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define meowler_ArmCommand_init_default          {false, 0, false, 0, false, 0, false, 0, false, 0}
#define meowler_ArmStatus_init_default           {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define meowler_ArmCommand_init_zero             {false, 0, false, 0, false, 0, false, 0, false, 0}
#define meowler_ArmStatus_init_zero              {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define meowler_ArmCommand_base_tag              1
#define meowler_ArmCommand_height_tag            2
#define meowler_ArmCommand_grip_tag              3
#define meowler_ArmCommand_speed_dps_tag         4
#define meowler_ArmCommand_action_tag            5
#define meowler_ArmStatus_base_tag               1
#define meowler_ArmStatus_height_tag             2
#define meowler_ArmStatus_grip_tag               3
#define meowler_ArmStatus_pca_ok_tag             4
#define meowler_ArmStatus_moving_tag             5
#define meowler_ArmStatus_distance_mm_tag        6
#define meowler_ArmStatus_tof_ok_tag             7
#define meowler_ArmStatus_imu_ok_tag             8
#define meowler_ArmStatus_yaw_cdeg_tag           9
#define meowler_ArmStatus_pitch_cdeg_tag         10
#define meowler_ArmStatus_roll_cdeg_tag          11

/* Struct field encoding specification for nanopb */
#define meowler_ArmCommand_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   base,              1) \
X(a, STATIC,   OPTIONAL, UINT32,   height,            2) \
X(a, STATIC,   OPTIONAL, UINT32,   grip,              3) \
X(a, STATIC,   OPTIONAL, UINT32,   speed_dps,         4) \
X(a, STATIC,   OPTIONAL, UINT32,   action,            5)
#define meowler_ArmCommand_CALLBACK NULL
#define meowler_ArmCommand_DEFAULT NULL

#define meowler_ArmStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   base,              1) \
X(a, STATIC,   SINGULAR, UINT32,   height,            2) \
X(a, STATIC,   SINGULAR, UINT32,   grip,              3) \
X(a, STATIC,   SINGULAR, BOOL,     pca_ok,            4) \
X(a, STATIC,   SINGULAR, BOOL,     moving,            5) \
X(a, STATIC,   SINGULAR, UINT32,   distance_mm,       6) \
X(a, STATIC,   SINGULAR, BOOL,     tof_ok,            7) \
X(a, STATIC,   SINGULAR, BOOL,     imu_ok,            8) \
X(a, STATIC,   SINGULAR, SINT32,   yaw_cdeg,          9) \
X(a, STATIC,   SINGULAR, SINT32,   pitch_cdeg,       10) \
X(a, STATIC,   SINGULAR, SINT32,   roll_cdeg,        11)
#define meowler_ArmStatus_CALLBACK NULL
#define meowler_ArmStatus_DEFAULT NULL

extern const pb_msgdesc_t meowler_ArmCommand_msg;
extern const pb_msgdesc_t meowler_ArmStatus_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define meowler_ArmCommand_fields &meowler_ArmCommand_msg
#define meowler_ArmStatus_fields &meowler_ArmStatus_msg

/* Maximum encoded size of messages (where known) */
#define MEOWLER_MEOWLER_PB_H_MAX_SIZE            meowler_ArmStatus_size
#define meowler_ArmCommand_size                  25
#define meowler_ArmStatus_size                   42

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
