/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "meowler.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(meowler_ArmCommand, meowler_ArmCommand, AUTO)


PB_BIND(meowler_ArmStatus, meowler_ArmStatus, AUTO)


PB_BIND(meowler_DriveCommand, meowler_DriveCommand, AUTO)


PB_BIND(meowler_DriveStatus, meowler_DriveStatus, AUTO)


PB_BIND(meowler_NanoCommand, meowler_NanoCommand, AUTO)


PB_BIND(meowler_NanoStatus, meowler_NanoStatus, AUTO)


PB_BIND(meowler_RobotCommand, meowler_RobotCommand, AUTO)


PB_BIND(meowler_RobotTelemetry, meowler_RobotTelemetry, AUTO)


PB_BIND(meowler_DebugLog, meowler_DebugLog, AUTO)


PB_BIND(meowler_LinkMessage, meowler_LinkMessage, AUTO)









