/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MEOWLER_MEOWLER_PB_H_INCLUDED
#define PB_MEOWLER_MEOWLER_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _meowler_Drive {
    int32_t left; /* -255..255 */
    int32_t right; /* -255..255 */
} meowler_Drive;

typedef struct _meowler_Arm {
    int32_t base; /* 0..180 */
    int32_t height; /* 0..180 */
    int32_t grip; /* 0..180 */
    bool set_base;
    bool set_height;
    bool set_grip;
} meowler_Arm;

typedef struct _meowler_ClientToRobot {
    pb_size_t which_op;
    union {
        meowler_Drive drive;
        meowler_Arm arm;
        bool stop;
        bool center;
        bool zero;
        bool motor_test;
        bool get_telem;
    } op;
} meowler_ClientToRobot;

typedef struct _meowler_Telemetry {
    uint32_t distance_mm;
    int32_t cmd_l;
    int32_t cmd_r;
    int32_t base;
    int32_t height;
    int32_t grip;
    bool pca_ok;
    bool tof_ok;
    bool imu_ok;
    bool wifi_ok;
    int32_t enc_l;
    int32_t enc_r;
    int32_t wheel_l_mm;
    int32_t wheel_r_mm;
    int32_t tof_disp_mm;
    int32_t yaw_cdeg;
    int32_t pitch_cdeg;
    int32_t roll_cdeg;
    uint32_t color; /* 0 none 1 red 2 yellow 3 green */
    uint32_t color_conf;
    uint32_t color_r; /* 0..100 */
    uint32_t color_g;
    uint32_t color_b;
    uint32_t color_rp; /* raw pulse us */
    uint32_t color_gp;
    uint32_t color_bp;
    uint32_t color_cp;
} meowler_Telemetry;

typedef struct _meowler_Hello {
    uint32_t ip; /* IPv4 as uint32 (network byte order) */
    uint32_t port;
    bool pca_ok;
    bool tof_ok;
    bool imu_ok;
} meowler_Hello;

typedef struct _meowler_RobotToClient {
    pb_size_t which_msg;
    union {
        meowler_Hello hello;
        meowler_Telemetry telem;
        uint32_t ack; /* 0 = ok */
    } msg;
} meowler_RobotToClient;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define meowler_Drive_init_default               {0, 0}
#define meowler_Arm_init_default                 {0, 0, 0, 0, 0, 0}
#define meowler_ClientToRobot_init_default       {0, {meowler_Drive_init_default}}
#define meowler_Telemetry_init_default           {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define meowler_Hello_init_default               {0, 0, 0, 0, 0}
#define meowler_RobotToClient_init_default       {0, {meowler_Hello_init_default}}
#define meowler_Drive_init_zero                  {0, 0}
#define meowler_Arm_init_zero                    {0, 0, 0, 0, 0, 0}
#define meowler_ClientToRobot_init_zero          {0, {meowler_Drive_init_zero}}
#define meowler_Telemetry_init_zero              {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define meowler_Hello_init_zero                  {0, 0, 0, 0, 0}
#define meowler_RobotToClient_init_zero          {0, {meowler_Hello_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define meowler_Drive_left_tag                   1
#define meowler_Drive_right_tag                  2
#define meowler_Arm_base_tag                     1
#define meowler_Arm_height_tag                   2
#define meowler_Arm_grip_tag                     3
#define meowler_Arm_set_base_tag                 4
#define meowler_Arm_set_height_tag               5
#define meowler_Arm_set_grip_tag                 6
#define meowler_ClientToRobot_drive_tag          1
#define meowler_ClientToRobot_arm_tag            2
#define meowler_ClientToRobot_stop_tag           3
#define meowler_ClientToRobot_center_tag         4
#define meowler_ClientToRobot_zero_tag           5
#define meowler_ClientToRobot_motor_test_tag     6
#define meowler_ClientToRobot_get_telem_tag      7
#define meowler_Telemetry_distance_mm_tag        1
#define meowler_Telemetry_cmd_l_tag              2
#define meowler_Telemetry_cmd_r_tag              3
#define meowler_Telemetry_base_tag               4
#define meowler_Telemetry_height_tag             5
#define meowler_Telemetry_grip_tag               6
#define meowler_Telemetry_pca_ok_tag             7
#define meowler_Telemetry_tof_ok_tag             8
#define meowler_Telemetry_imu_ok_tag             9
#define meowler_Telemetry_wifi_ok_tag            10
#define meowler_Telemetry_enc_l_tag              11
#define meowler_Telemetry_enc_r_tag              12
#define meowler_Telemetry_wheel_l_mm_tag         13
#define meowler_Telemetry_wheel_r_mm_tag         14
#define meowler_Telemetry_tof_disp_mm_tag        15
#define meowler_Telemetry_yaw_cdeg_tag           16
#define meowler_Telemetry_pitch_cdeg_tag         17
#define meowler_Telemetry_roll_cdeg_tag          18
#define meowler_Telemetry_color_tag              19
#define meowler_Telemetry_color_conf_tag         20
#define meowler_Telemetry_color_r_tag            21
#define meowler_Telemetry_color_g_tag            22
#define meowler_Telemetry_color_b_tag            23
#define meowler_Telemetry_color_rp_tag           24
#define meowler_Telemetry_color_gp_tag           25
#define meowler_Telemetry_color_bp_tag           26
#define meowler_Telemetry_color_cp_tag           27
#define meowler_Hello_ip_tag                     1
#define meowler_Hello_port_tag                   2
#define meowler_Hello_pca_ok_tag                 3
#define meowler_Hello_tof_ok_tag                 4
#define meowler_Hello_imu_ok_tag                 5
#define meowler_RobotToClient_hello_tag          1
#define meowler_RobotToClient_telem_tag          2
#define meowler_RobotToClient_ack_tag            3

/* Struct field encoding specification for nanopb */
#define meowler_Drive_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    left,              1) \
X(a, STATIC,   SINGULAR, INT32,    right,             2)
#define meowler_Drive_CALLBACK NULL
#define meowler_Drive_DEFAULT NULL

#define meowler_Arm_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    base,              1) \
X(a, STATIC,   SINGULAR, INT32,    height,            2) \
X(a, STATIC,   SINGULAR, INT32,    grip,              3) \
X(a, STATIC,   SINGULAR, BOOL,     set_base,          4) \
X(a, STATIC,   SINGULAR, BOOL,     set_height,        5) \
X(a, STATIC,   SINGULAR, BOOL,     set_grip,          6)
#define meowler_Arm_CALLBACK NULL
#define meowler_Arm_DEFAULT NULL

#define meowler_ClientToRobot_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (op,drive,op.drive),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (op,arm,op.arm),   2) \
X(a, STATIC,   ONEOF,    BOOL,     (op,stop,op.stop),   3) \
X(a, STATIC,   ONEOF,    BOOL,     (op,center,op.center),   4) \
X(a, STATIC,   ONEOF,    BOOL,     (op,zero,op.zero),   5) \
X(a, STATIC,   ONEOF,    BOOL,     (op,motor_test,op.motor_test),   6) \
X(a, STATIC,   ONEOF,    BOOL,     (op,get_telem,op.get_telem),   7)
#define meowler_ClientToRobot_CALLBACK NULL
#define meowler_ClientToRobot_DEFAULT NULL
#define meowler_ClientToRobot_op_drive_MSGTYPE meowler_Drive
#define meowler_ClientToRobot_op_arm_MSGTYPE meowler_Arm

#define meowler_Telemetry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   distance_mm,       1) \
X(a, STATIC,   SINGULAR, INT32,    cmd_l,             2) \
X(a, STATIC,   SINGULAR, INT32,    cmd_r,             3) \
X(a, STATIC,   SINGULAR, INT32,    base,              4) \
X(a, STATIC,   SINGULAR, INT32,    height,            5) \
X(a, STATIC,   SINGULAR, INT32,    grip,              6) \
X(a, STATIC,   SINGULAR, BOOL,     pca_ok,            7) \
X(a, STATIC,   SINGULAR, BOOL,     tof_ok,            8) \
X(a, STATIC,   SINGULAR, BOOL,     imu_ok,            9) \
X(a, STATIC,   SINGULAR, BOOL,     wifi_ok,          10) \
X(a, STATIC,   SINGULAR, INT32,    enc_l,            11) \
X(a, STATIC,   SINGULAR, INT32,    enc_r,            12) \
X(a, STATIC,   SINGULAR, INT32,    wheel_l_mm,       13) \
X(a, STATIC,   SINGULAR, INT32,    wheel_r_mm,       14) \
X(a, STATIC,   SINGULAR, INT32,    tof_disp_mm,      15) \
X(a, STATIC,   SINGULAR, INT32,    yaw_cdeg,         16) \
X(a, STATIC,   SINGULAR, INT32,    pitch_cdeg,       17) \
X(a, STATIC,   SINGULAR, INT32,    roll_cdeg,        18) \
X(a, STATIC,   SINGULAR, UINT32,   color,            19) \
X(a, STATIC,   SINGULAR, UINT32,   color_conf,       20) \
X(a, STATIC,   SINGULAR, UINT32,   color_r,          21) \
X(a, STATIC,   SINGULAR, UINT32,   color_g,          22) \
X(a, STATIC,   SINGULAR, UINT32,   color_b,          23) \
X(a, STATIC,   SINGULAR, UINT32,   color_rp,         24) \
X(a, STATIC,   SINGULAR, UINT32,   color_gp,         25) \
X(a, STATIC,   SINGULAR, UINT32,   color_bp,         26) \
X(a, STATIC,   SINGULAR, UINT32,   color_cp,         27)
#define meowler_Telemetry_CALLBACK NULL
#define meowler_Telemetry_DEFAULT NULL

#define meowler_Hello_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ip,                1) \
X(a, STATIC,   SINGULAR, UINT32,   port,              2) \
X(a, STATIC,   SINGULAR, BOOL,     pca_ok,            3) \
X(a, STATIC,   SINGULAR, BOOL,     tof_ok,            4) \
X(a, STATIC,   SINGULAR, BOOL,     imu_ok,            5)
#define meowler_Hello_CALLBACK NULL
#define meowler_Hello_DEFAULT NULL

#define meowler_RobotToClient_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,hello,msg.hello),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,telem,msg.telem),   2) \
X(a, STATIC,   ONEOF,    UINT32,   (msg,ack,msg.ack),   3)
#define meowler_RobotToClient_CALLBACK NULL
#define meowler_RobotToClient_DEFAULT NULL
#define meowler_RobotToClient_msg_hello_MSGTYPE meowler_Hello
#define meowler_RobotToClient_msg_telem_MSGTYPE meowler_Telemetry

extern const pb_msgdesc_t meowler_Drive_msg;
extern const pb_msgdesc_t meowler_Arm_msg;
extern const pb_msgdesc_t meowler_ClientToRobot_msg;
extern const pb_msgdesc_t meowler_Telemetry_msg;
extern const pb_msgdesc_t meowler_Hello_msg;
extern const pb_msgdesc_t meowler_RobotToClient_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define meowler_Drive_fields &meowler_Drive_msg
#define meowler_Arm_fields &meowler_Arm_msg
#define meowler_ClientToRobot_fields &meowler_ClientToRobot_msg
#define meowler_Telemetry_fields &meowler_Telemetry_msg
#define meowler_Hello_fields &meowler_Hello_msg
#define meowler_RobotToClient_fields &meowler_RobotToClient_msg

/* Maximum encoded size of messages (where known) */
#define MEOWLER_MEOWLER_PB_H_MAX_SIZE            meowler_RobotToClient_size
#define meowler_Arm_size                         39
#define meowler_ClientToRobot_size               41
#define meowler_Drive_size                       22
#define meowler_Hello_size                       18
#define meowler_RobotToClient_size               226
#define meowler_Telemetry_size                   223

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
