/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "meowler.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(meowler_Drive, meowler_Drive, AUTO)


PB_BIND(meowler_Arm, meowler_Arm, AUTO)


PB_BIND(meowler_Conveyor, meowler_Conveyor, AUTO)


PB_BIND(meowler_ColorCal, meowler_ColorCal, AUTO)


PB_BIND(meowler_RecCtrl, meowler_RecCtrl, AUTO)


PB_BIND(meowler_RecEvent, meowler_RecEvent, AUTO)


PB_BIND(meowler_OtaBegin, meowler_OtaBegin, AUTO)


PB_BIND(meowler_OtaChunk, meowler_OtaChunk, 4)


PB_BIND(meowler_OtaCmd, meowler_OtaCmd, 4)


PB_BIND(meowler_OtaStatus, meowler_OtaStatus, AUTO)


PB_BIND(meowler_ClientToRobot, meowler_ClientToRobot, 4)


PB_BIND(meowler_Telemetry, meowler_Telemetry, AUTO)


PB_BIND(meowler_Hello, meowler_Hello, AUTO)


PB_BIND(meowler_Log, meowler_Log, AUTO)


PB_BIND(meowler_RobotToClient, meowler_RobotToClient, AUTO)



